// <auto-generated />
namespace MVC_CSV_DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBAnagraficaIcp1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBAnagraficaIcp1));
        
        string IMigrationMetadata.Id
        {
            get { return "202103241033270_DBAnagraficaIcp1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
